version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: siqueira-fix-app
    environment:
      - NODE_ENV=production
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET:-webhook-secret-123}
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - fix-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/ping"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s

  nginx:
    image: nginx:alpine
    container_name: siqueira-fix-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-mobile-fix.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - fix-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost/health",
        ]
      interval: 30s
      timeout: 5s
      retries: 2

networks:
  fix-network:
    driver: bridge
