version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: siqueira-postgres
    environment:
      POSTGRES_DB: bdsitejuarez
      POSTGRES_USER: sitejuarez
      POSTGRES_PASSWORD: juarez123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sitejuarez -d bdsitejuarez"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: siqueira-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    container_name: siqueira-app
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://sitejuarez:juarez123@postgres:5432/bdsitejuarez?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=468465454567653554546524
      - JWT_EXPIRES_IN=7d
      - COOKIE_SECRET=645454564867654575565
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USER=siqueiraecamposimoveisgoiania@gmail.com
      - EMAIL_PASS=Juarez.123
      - GOOGLE_CLIENT_ID=7452076957-v6740revpqo1s3f0ek25dr1tpua6q893.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - GOOGLE_CALLBACK_URL=https://siqueicamposimoveis.com.br/api/auth/google/callback
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    container_name: siqueira-n8n
    ports:
      - "5678:5678"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=sitejuarez
      - DB_POSTGRESDB_PASSWORD=juarez123
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=siqueira2024
      - WEBHOOK_URL=https://n8n.siqueicamposimoveis.com.br
      - GENERIC_TIMEZONE=America/Sao_Paulo
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n-fluxo-imobiliaria-completo.json:/home/node/.n8n/workflows/
    restart: unless-stopped

  evolution-api:
    image: atendai/evolution-api:latest
    container_name: siqueira-evolution
    ports:
      - "8080:8080"
    environment:
      - SERVER_TYPE=http
      - SERVER_PORT=8080
      - CORS_ORIGIN=*
      - CORS_METHODS=GET,POST,PUT,DELETE
      - CORS_CREDENTIALS=true
      - LOG_LEVEL=ERROR
      - LOG_COLOR=true
      - LOG_BAILEYS=error
      - DEL_INSTANCE=false
      - PROVIDER_ENABLED=true
      - PROVIDER_HOST=http://localhost
      - PROVIDER_PORT=8080
      - PROVIDER_PREFIX=evolution
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=siqueira_evolution_2024
      - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=true
      - QRCODE_LIMIT=30
      - QRCODE_COLOR=#198754
      - TYPEBOT_ENABLED=false
      - CHATWOOT_ENABLED=false
      - WEBSOCKET_ENABLED=false
      - RABBITMQ_ENABLED=false
      - SQS_ENABLED=false
      - WEBHOOK_GLOBAL_URL=http://n8n:5678/webhook/resposta-corretor
      - WEBHOOK_GLOBAL_ENABLED=true
      - WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS=false
      - CONFIG_SESSION_PHONE_CLIENT=Siqueira Campos
      - CONFIG_SESSION_PHONE_NAME=Chrome
    volumes:
      - evolution_data:/evolution/instances
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: siqueira-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
      - n8n
      - evolution-api
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  n8n_data:
  evolution_data:

networks:
  default:
    name: siqueira-network
