version: "3.8"

services:
  # PostgreSQL para desenvolvimento
  postgres-dev:
    image: postgres:16-alpine
    container_name: postgres_dev
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: siqueicampos_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d siqueicampos_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis para desenvolvimento
  redis-dev:
    image: redis:7-alpine
    container_name: redis_dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    command: redis-server --appendonly yes

  # Adminer para gerenciar banco
  adminer-dev:
    image: adminer:latest
    container_name: adminer_dev
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres-dev

volumes:
  postgres_dev_data:
  redis_dev_data:

networks:
  default:
    name: siqueicampos_dev
