global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "docker"
    static_configs:
      - targets: ["172.17.0.1:9323"]

  - job_name: "traefik"
    static_configs:
      - targets: ["traefik:8080"]

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:5432"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]

  - job_name: "n8n"
    static_configs:
      - targets: ["n8n:5678"]

  - job_name: "evolution-api"
    static_configs:
      - targets: ["evolution-api:8080"]

  - job_name: "minio"
    static_configs:
      - targets: ["minio:9000"]

  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]
